### ISSUE TITLE
Selecting "Feed" now errors

### ISSUE THREAD

**Issue by cw-kid** [winsomehax/plugin.video.bitchute#24]
This was working but now when selecting the "Feed" option Kodi pops up an error message. 

Had a look in the Kodi log I found these:

`2021-01-12 20:18:19.897 T:140512735303424   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: get_channel() takes exactly 2 arguments (1 given)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.bitchute/main.py", line 4, in <module>
                                                kodi_bitchute.plugin.run()
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.bitchute/kodi_bitchute.py", line 73, in feed
                                                build_feed()
                                              File "/storage/.kodi/addons/plugin.video.bitchute/kodi_bitchute.py", line 229, in build_feed
                                                entries = bitchute_access.get_feed()
                                              File "/storage/.kodi/addons/plugin.video.bitchute/bitchute_access.py", line 580, in get_feed
                                                return pickle.loads(data_cache.cacheFunction(_get_feed, cookies))
                                              File "/storage/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/StorageServer.py", line 623, in cacheFunction
                                                ret_val = funct(*args)
                                              File "/storage/.kodi/addons/plugin.video.bitchute/bitchute_access.py", line 389, in _get_feed
                                                channel = get_channel(sub.channel)
                                            TypeError: get_channel() takes exactly 2 arguments (1 given)
                                            -->End of Python script error report<--`

`2021-01-12 20:18:19.897 T:140512735303424   DEBUG: onExecutionDone(400, /storage/.kodi/addons/plugin.video.bitchute/main.py)
2021-01-12 20:18:19.926 T:140515488147584   DEBUG: ------ Window Init (DialogNotification.xml) ------
2021-01-12 20:18:19.980 T:140512735303424    INFO: Python interpreter stopped
2021-01-12 20:18:19.980 T:140512735303424   DEBUG: Thread LanguageInvoker 140512735303424 terminating
2021-01-12 20:18:19.983 T:140512908523264   ERROR: GetDirectory - Error getting plugin://plugin.video.bitchute/feed?item_val=None
2021-01-12 20:18:19.983 T:140512908523264   DEBUG: Thread waiting 140512908523264 terminating
2021-01-12 20:18:19.992 T:140515488147584   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2021-01-12 20:18:19.994 T:140515488147584   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.bitchute/feed?item_val=None) failed
2021-01-12 20:18:19.994 T:140515488147584   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.bitchute/)
2021-01-12 20:18:19.994 T:140515488147584   DEBUG:   ParentPath = [plugin://]
2021-01-12 20:18:19.994 T:140512908523264   DEBUG: Thread waiting start, auto delete: false
2021-01-12 20:18:20.006 T:140513193744128   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.bitchute] took 13 ms
2021-01-12 20:18:20.006 T:140512908523264   DEBUG: StartScript - calling plugin bitchute('plugin://plugin.video.bitchute/','325','','resume:false')
2021-01-12 20:18:20.007 T:140512735303424   DEBUG: Thread LanguageInvoker start, auto delete: false
2021-01-12 20:18:20.007 T:140512735303424    INFO: initializing python engine.
2021-01-12 20:18:20.007 T:140512735303424   DEBUG: CPythonInvoker(401, /storage/.kodi/addons/plugin.video.bitchute/main.py): start processing
2021-01-12 20:18:20.014 T:140512735303424   DEBUG: -->Python Interpreter Initialized<--
2021-01-12 20:18:20.014 T:140512735303424   DEBUG: CPythonInvoker(401, /storage/.kodi/addons/plugin.video.bitchute/main.py): the source file to load is "/storage/.kodi/addons/plugin.video.bitchute/main.py"`

Thanks

**Comment by winsomehax** [comment]
This should work now.

**Comment by cw-kid** [comment]
I downloaded and installed again the Testing branch version. 

Selecting the "Feed" item it now loads up one page of videos again. However it did take quite a while with a spinning circle on screen, before the videos appeared in a list. 

Thanks.

**Comment by winsomehax** [comment]
Yeah it is a very long winded process. It takes the latest video from each
of your subscriptions. It has to load each subscription and scrape the top
entry. Not great, but bitchute doesn't appear to have a 'feed' as such. So
I have to fake one.

**Comment by winsomehax** [comment]
Fixed
