### ISSUE TITLE
Unable to load feed

### ISSUE THREAD

**Issue by dagfinnr1** [winsomehax/plugin.video.bitchute#45]
Subscriptions open but when you click on feed just spins and spins for about 30 secs then says bitchute error refer to log.

**Comment by winsomehax** [comment]
thanks for reporting this. Apologies for taking some time... I've been ill. 

I've tried to repeat it on my system but can't. If it's still doing it, can you send the log.

**Comment by dagfinnr1** [comment]
Sorry for taking so long to reply. Anyways it still does it. Here is the error as found in the log. Thanks!

2021-11-03 21:00:14.074 T:3308 ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'IndexError'>
Error Contents: list index out of range
Traceback (most recent call last):
File "C:\Users\HTPC\AppData\Roaming\Kodi\addons\plugin.video.bitchute\main.py", line 4, in <module>
kodi_bitchute.plugin.run()
File "C:\Users\HTPC\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
self._dispatch(self.path)
File "C:\Users\HTPC\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
view_func(**kwargs)
File "C:\Users\HTPC\AppData\Roaming\Kodi\addons\plugin.video.bitchute\kodi_bitchute.py", line 73, in feed
build_feed()
File "C:\Users\HTPC\AppData\Roaming\Kodi\addons\plugin.video.bitchute\kodi_bitchute.py", line 205, in build_feed
entries = bitchute_access.get_feed()
File "C:\Users\HTPC\AppData\Roaming\Kodi\addons\plugin.video.bitchute\bitchute_access.py", line 627, in get_feed
return pickle.loads(data_cache.cacheFunction(_get_feed, cookies))
File "C:\Users\HTPC\AppData\Roaming\Kodi\addons\script.common.plugin.cache\resources\lib\storage_server\StorageServer.py", line 628, in cacheFunction
ret_val = funct(*args)
File "C:\Users\HTPC\AppData\Roaming\Kodi\addons\plugin.video.bitchute\bitchute_access.py", line 437, in _get_feed
vid = channel[0] # The latest video
IndexError: list index out of range
-->End of Python script error report<--

2021-11-03 21:00:14.204 T:3308 INFO <general>: Python interpreter stopped
2021-11-03 21:00:14.208 T:2900 ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.bitchute/feed?item_val=None
2021-11-03 21:00:14.219 T:7232 ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.bitchute/feed?item_val=None) failed
2021-11-03 21:01:30.277 T:8604 INFO <general>: JSONRPC Server: New connection added
2021-11-03 21:01:30.308 T:8604 INFO <general>: JSONRPC Server: Disconnection detected
2021-11-03 21:01:52.799 T:8600 INFO <general>: ES: Client from ::ffff:192.168.1.189 timed out
2021-11-03 21:02:03.410 T:8604 INFO <general>: JSONRPC Server: Disconnection detected

Sent from ProtonMail mobile

-------- Original Message --------
