### ISSUE TITLE
Plugin stopped working on LibreELEC 9.2.8 on Raspberry 3

### ISSUE THREAD

**Issue by jk-85** [winsomehax/plugin.video.bitchute#47]
I have LibreELEC 9.2.8  on a Raspberry 3 and the plugin stopped working.  The log-file says this:

> /storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
                                              'The soupsieve package is not installed. CSS selectors cannot be used.'
2022-06-29 10:23:00.201 T:1423324032   ERROR: Previous line repeats 4 times.
2022-06-29 10:23:00.202 T:1423324032   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe4' in position 36: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.bitchute/main.py", line 4, in <module>
                                                kodi_bitchute.plugin.run()
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.bitchute/kodi_bitchute.py", line 67, in play_now
                                                play_video(item_val)
                                              File "/storage/.kodi/addons/plugin.video.bitchute/kodi_bitchute.py", line 278, in play_video
                                                v = bitchute_access.get_video(video_id)
                                              File "/storage/.kodi/addons/plugin.video.bitchute/bitchute_access.py", line 655, in get_video
                                                return pickle.loads(data_cache.cacheFunction(_get_video, cookies, video_id))
                                              File "/storage/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/StorageServer.py", line 628, in cacheFunction
                                                ret_val = funct(*args)
                                              File "/storage/.kodi/addons/plugin.video.bitchute/bitchute_access.py", line 524, in _get_video
                                                title = str(soup.find(id="video-title").contents[0])
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 36: ordinal not in range(128)
                                            -->End of Python script error report<--
2022-06-29 10:23:00.486 T:1383035776   ERROR: GetDirectory - Error getting plugin://plugin.video.bitchute/play_now/mr3SChgzqaeU
2022-06-29 10:23:00.491 T:1937031232   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.bitchute/play_now/mr3SChgzqaeU) failed

**Comment by jk-85** [comment]
Bitchute plugin vesion: 2.2.0

**Comment by Slavegrid** [comment]
_get_video has been recently updated. It should be working now.
