### ISSUE TITLE
Error Parsing

### ISSUE THREAD

**Issue by EvilCaptKirk** [winsomehax/plugin.video.bitchute#54]
At some recent point, things went from fully working to getting 'error parsing' on any menu item that has to locate and present certain listings: subscription items (not channels, but the videos within any subscribed channel), search results, feed menu. The issue exists on both 19.x and 20.x branches of Kodi, though the affected menu items might differ a bit.

Search creates an error in the log as follows:

 -->Python callback/script returned the following error<--
    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
   Error Type: <class 'KeyError'>
   Error Contents: 'results'
   Traceback (most recent call last):
     File "C:\...\addons\plugin.video.bitchute\main.py", line 4, in <module>
       kodi_bitchute.plugin.run()
     File "C:\...\addons\script.module.routing\lib\routing.py", line 130, in run
       self._dispatch(self.path)
     File "C:\...\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
       view_func(**kwargs)
     File "C:\...\addons\plugin.video.bitchute\kodi_bitchute.py", line 93, in search
       build_search()
     File "C:\...\addons\plugin.video.bitchute\kodi_bitchute.py", line 262, in build_search
       results = bitchute_access.search(d)
     File "C:\...\addons\plugin.video.bitchute\bitchute_access.py", line 636, in search
       return pickle.loads(data_cache.cacheFunction(_search, cookies, search_for))
     File "C:\...\addons\script.common.plugin.cache\resources\lib\storage_server\StorageServer.py", line 628, in cacheFunction
       ret_val = funct(*args)
     File "C:\...\addons\plugin.video.bitchute\bitchute_access.py", line 553, in _search
       for result in val["results"]:
   KeyError: 'results'
-->End of Python script error report<--

**Comment by Slavegrid** [comment]
Search should be fixed in the v2.3.1 release.
