### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by jk-85** [winsomehax/plugin.video.bitchute#58]
Is it still broken? Have newest KODI and LibreELEC version now but can't get it to work, After I input my username and password I got this log entry:

> 2024-07-26 19:40:49.538 T:880      info <general>: Skipped 1 duplicate messages..
2024-07-26 19:40:49.538 T:880   warning <general>: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2024-07-26 19:40:50.491 T:1046    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: "name='csrftoken', domain=None, path=None"
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.bitchute/main.py", line 4, in <module>
                                                       kodi_bitchute.plugin.run()
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.bitchute/kodi_bitchute.py", line 88, in open_settings
                                                       build_open_settings()
                                                     File "/storage/.kodi/addons/plugin.video.bitchute/kodi_bitchute.py", line 284, in build_open_settings
                                                       bitchute_access.bt_login()
                                                     File "/storage/.kodi/addons/plugin.video.bitchute/bitchute_access.py", line 139, in bt_login
                                                       pickled_cookies, success = login_cache.cacheFunction(
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/StorageServer.py", line 609, in cacheFunction
                                                       ret_val = funct(*args)
                                                                 ^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.bitchute/bitchute_access.py", line 115, in BitchuteLogin
                                                       token = req.cookies["csrftoken"]
                                                               ~~~~~~~~~~~^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/cookies.py", line 334, in __getitem__
                                                       return self._find_no_duplicates(name)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/cookies.py", line 413, in _find_no_duplicates
                                                       raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
                                                   KeyError: "name='csrftoken', domain=None, path=None"
                                                   -->End of Python script error report<--

> 2024-07-26 19:40:50.997 T:1045    error <general>: GetDirectory - Error getting plugin://plugin.video.bitchute/open_settings?item_val=None
2024-07-26 19:40:51.006 T:880     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.bitchute/open_settings?item_val=None) failed

**Comment by karlo2105** [comment]
As long as @SethEddy patch is not pushed by @winsomehax, you shall apply manually patch or install patched plugin from @SethEddy from [here](https://github.com/SethEddy/plugin.video.bitchute/archive/refs/heads/patch-1.zip)

**Comment by Slavegrid** [comment]
I have a Kodi repo which contains a patched version of this addon + other addons for Odysee and Rumble at https://slavegrid.com

**Comment by winsomehax** [comment]
> I have a Kodi repo which contains a patched version of this addon + other addons for Odysee and Rumble at https://slavegrid.com

Glad someone has put it in a repo. Happy to mention this on this repos front page.

**Comment by karlo2105** [comment]
@Slavegrid
You can add [Lbryplus](https://github.com/azzy9/plugin.video.lbryplus) to your repo, which is enhanced and patched version of Lbry also from azzy9.

**Comment by Slavegrid** [comment]
> @Slavegrid You can add [Lbryplus](https://github.com/azzy9/plugin.video.lbryplus) to your repo, which is enhanced and patched version of Lbry also from azzy9.

plugin.video.lbry.sg in the repo is a similar fork to azzy9 and slightly predates his. I believe my addon has more functionality and bug fixes: user notifications, Livestream notifications, video voting, ability to locally install/run lbrynet instance from the addon, improved search, synced playlists, channel/playlist export/import, fixed sound stuttering on the comment page and lots of other smaller bug fixes.

**Comment by jk-85** [comment]
@winsomehax Great, thank you for the info!
